import Helpers
import Categories
import CwF-Structure
import Yoneda
import Types.Discrete
import Types.Functions
import Types.Products
import Types.Sums
import LiftingFunctors
import GuardedRecursion.Later
import GuardedRecursion.StreamsExample
import Reflection.Helpers
import Reflection.Substitutions
import Reflection.Types
import Reflection.Naturality
import Reflection.NaturalityTactic
